# fly.toml app configuration file generated for earthly-go-example on 2023-07-26T21:07:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "earthly-go-example"
primary_region = "lax"

[build]
  image = "ezeev/earthly-go-example:ci-demo"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
