name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.9
      - uses: actions/checkout@v2
      - name: Earthly version
        run: earthly --version
      - name: Run CI pipeline (tests)
        run: |
          earthly --ci +all-test
          earthly --ci +build-services --tag=ci-demo
